### PR TITLE
Added a schedule section

### PR DESCRIPTION
**Pull request by netochaves**
Added a new section with the event schedule.

image

### CODE REVIEW

**Comment by willamesoares** [comment]
Noticed two things here

Can we keep the talk title in the speaker card please?
Screen Shot 2019-09-10 at 12 25 46 AM

The schedule section is not entirely responsive, right? Do you mind doing some adjustments so it can look a little better? :)
Screen Shot 2019-09-10 at 12 26 41 AM

**Comment by netochaves** [comment]
Sure!

**Comment by netochaves** [comment]
> Noticed two things here
> 
> Can we keep the talk title in the speaker card please?
> Screen Shot 2019-09-10 at 12 25 46 AM

Done.

> The schedule section is not entirely responsive, right? Do you mind doing some adjustments so it can look a little better? :)
> Screen Shot 2019-09-10 at 12 26 41 AM

Any ideas on how to be more responsive? I could not reproduce this behavior either, can you share the resolution?

**Comment by willamesoares** [comment]
I think for mobile devices we could remove the `Icon` (allowing the talk title block to grow horizontally) and also remove the expanding behavior so we'd only show the time and talk title/ speaker name in row direction. What do you think?
btw, the screenshot is on iPhone ~7~ 5

**Pull request merged**
